ONE = (
    'artless',
    'bawdy',
    'beslubbering',
    'bootless',
    'churlish',
    'cockered',
    'clouted',
    'craven',
    'currish',
    'dankish',
    'dissembling',
    'droning',
    'errant',
    'fawning',
    'fobbing',
    'froward',
    'frothy',
    'gleeking',
    'goatish',
    'gorbellied',
    'impertinent',
    'infectious',
    'jarring',
    'loggerheaded',
    'lumpish',
    'mammering',
    'mangled',
    'mewling',
    'paunchy',
    'pribbling',
    'puking',
    'puny',
    'qualling',
    'rank',
    'reeky',
    'roguish',
    'ruttish',
    'saucy',
    'spleeny',
    'spongy',
    'surly',
    'tottering',
    'unmuzzled',
    'vain',
    'venomed',
    'villainous',
    'warped',
    'wayward',
    'weedy',
    'yeasty',
    'cullionly',
    'fusty',
    'caluminous',
    'wimpled',
    'burly-boned',
    'misbegotten',
    'odiferous',
    'poisonous',
    'fishified',
    'wart-necked',
)

TWO = (
    'base-court',
    'bat-fowling',
    'beef-witted',
    'beetle-headed',
    'boil-brained',
    'clapper-clawed',
    'clay-brained',
    'common-kissing',
    'crook-pated',
    'dismal-dreaming',
    'dizzy-eyed',
    'doghearted',
    'dread-bolted',
    'earth-vexing',
    'elf-skinned',
    'fat-kidneyed',
    'fen-sucked',
    'flap-mouthed',
    'fly-bitten',
    'folly-fallen',
    'fool-born',
    'full-gorged',
    'guts-griping',
    'half-faced',
    'hasty-witted',
    'hedge-born',
    'hell-hated',
    'idle-headed',
    'ill-breeding',
    'ill-nurtured',
    'knotty-pated',
    'milk-livered',
    'motley-minded',
    'onion-eyed',
    'plume-plucked',
    'pottle-deep',
    'pox-marked',
    'reeling-ripe',
    'rough-hewn',
    'rude-growing',
    'rump-fed',
    'shard-borne',
    'sheep-biting',
    'spur-galled',
    'swag-bellied',
    'tardy-gaited',
    'tickle-brained',
    'toad-spotted',
    'unchin-snouted',
    'weather-bitten',
    'whoreson',
    'malmsey-nosed',
    'rampallian',
    'lily-livered',
    'scurvy-valiant',
    'brazen-faced',
    'unwash\'d',
    'bunch-back\'d',
    'leaden-footed',
    'muddy-mettled',
    'pigeon-liver\'d',
    'scale-sided',
)

THREE = (
    'apple-john',
    'baggage',
    'barnacle',
    'bladder',
    'boar-pig',
    'bugbear',
    'bum-bailey',
    'canker-blossom',
    'clack-dish',
    'clotpole',
    'coxcomb',
    'codpiece',
    'death-token',
    'dewberry',
    'flap-dragon',
    'flax-wench',
    'flirt-gill',
    'foot-licker',
    'fustilarian',
    'giglet',
    'gudgeon',
    'haggard',
    'harpy',
    'hedge-pig',
    'horn-beast',
    'hugger-mugger',
    'joithead',
    'lewdster',
    'lout',
    'maggot-pie',
    'malt-worm',
    'mammet',
    'measle',
    'minnow',
    'miscreant',
    'moldwarp',
    'mumble-news',
    'nut-hook',
    'pigeon-egg',
    'pignut',
    'puttock',
    'pumpion',
    'ratsbane',
    'scut',
    'skainsmate',
    'strumpet',
    'varlot',
    'vassal',
    'whey-face',
    'wagtail',
    'knave',
    'blind-worm',
    'popinjay',
    'scullian',
    'jolt-head',
    'malcontent',
    'devil-monk',
    'toad',
    'rascal',
    'basket-Cockle',
)

FULL_INSULTS = (
    'Thou clay-brained guts, thou knotty-pated fool, thou whoreson obscene greasy tallow-catch!',
    'Methink\'st thou art a general offence and every man should beat thee.',
    'A most notable coward, an infinite and endless liar, an hourly promise breaker, the owner of no one good quality.',
    'Thy sin\'s not accidental, but a trade.',
    'If thou wilt needs marry, marry a fool; for wise men know well enough what monsters you make of them.',
    'You are as a candle, the better burnt out.',
    'Your brain is as dry as the remainder biscuit after voyage.',
    'Thine face is not worth sunburning.',
    'Your virginity breeds mites, much like a cheese.',
    'Thou art a pigeon-liver\'d and lack gall.',
    'Thou art unfit for any place but hell.',
    'Thou poisonous bunch-back\'d toad!',
    'There\'s no more faith in thee than in a stewed prune.',
    'Peace, ye fat guts!',
    'Thou clay-brained guts, thou knotty-pated fool, thou whoreson obscene greasy tallow-catch!',
    'Go, prick thy face, and over-red thy fear, Thou lily-liver\'d boy.',
    'Thou art as loathsome as a toad.',
    'My wife\'s a hobby horse!',
    'Methink\'st thou art a general offence and every man should beat thee.',
    'You scullion! You rampallian! You fustilarian! I\'ll tickle your catastrophe!',
    'Thy tongue outvenoms all the worms of Nile.',
    'A most notable coward, an infinite and endless liar, an hourly promise breaker, the owner of no one good quality.',
    'Thou art a flesh-monger, a fool and a coward.',
    'Thine forward voice, now, is to speak well of thine friend; thine backward voice is to utter foul speeches and to detract.',
    'Thou art like a toad; ugly and venemous.',
    'Thou subtle, perjur\'d, false, disloyal man!',
)
